// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxvnbtlwzmxomckedjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeHZuYnRsd3pteG9tY2tlZGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNDczNzcsImV4cCI6MjA0OTgyMzM3N30.tMfQAehlHOPU0HXjkioEnb6FMzO0Pdq_ejsF-g7dxhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);